"""empty message

Revision ID: 3cefbe74f5aa
Revises: None
Create Date: 2015-11-04 11:09:56.355960

"""

# revision identifiers, used by Alembic.
revision = '3cefbe74f5aa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_date_created'), 'users', ['date_created'], unique=False)
    op.create_index(op.f('ix_users_date_modified'), 'users', ['date_modified'], unique=False)
    op.create_table('bucketlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_bucketlists_date_created'), 'bucketlists', ['date_created'], unique=False)
    op.create_index(op.f('ix_bucketlists_date_modified'), 'bucketlists', ['date_modified'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('bucketlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bucketlist_id'], ['bucketlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_items_date_created'), 'items', ['date_created'], unique=False)
    op.create_index(op.f('ix_items_date_modified'), 'items', ['date_modified'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_date_modified'), table_name='items')
    op.drop_index(op.f('ix_items_date_created'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_bucketlists_date_modified'), table_name='bucketlists')
    op.drop_index(op.f('ix_bucketlists_date_created'), table_name='bucketlists')
    op.drop_table('bucketlists')
    op.drop_index(op.f('ix_users_date_modified'), table_name='users')
    op.drop_index(op.f('ix_users_date_created'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
