"""empty message

Revision ID: 455cfe3eca24
Revises: 3cefbe74f5aa
Create Date: 2015-11-04 15:42:04.597681

"""

# revision identifiers, used by Alembic.
revision = '455cfe3eca24'
down_revision = '3cefbe74f5aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bucketlists', ['id'])
    op.create_unique_constraint(None, 'items', ['id'])
    op.add_column('users', sa.Column('email', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'items', type_='unique')
    op.drop_constraint(None, 'bucketlists', type_='unique')
    ### end Alembic commands ###
